// src/routes/api/+page.svelte
<script>
	import Container from '$lib/components/container.svelte';
</script>

<svelte:head>
	<title>API - isave</title>
</svelte:head>

<main class="grid place-items-center">
	<Container>
		<section class="space-y-4">
			<div class="space-y-4">
				<h1 class="text-3xl font-semibold">Interested in using our API?</h1>

				<p class="text-lg">
					Email us with the subject “I want to use isave API” and your estimated monthly server
					requests. We’ll review your needs to ensure compatibility and collaborate on achieving
					your goals.
				</p>

				<a
					href="https://rraghavan.com/"
					target="_blank"
					rel="noopener noreferrer"
					class="border-b border-black after:content-['_↗']"
				>
					Contact me
				</a>
			</div>
		</section>
	</Container>
</main>

// app/web/api/page.tsx
import Container from "../../../components/container";
import Section from "./section";

function ApiPage() {
  return (
    <main className="grid place-items-center p-4">
      <Container>
        <p className="text-center leading-7">
          If you are interested in using our API, I would be happy to discuss
          the details with you. Please send us an email with the subject &quot;I
          want to use isave api&quot; and include information about your monthly
          server request average. This will allow us to better understand your
          needs and determine if our API is the right fit for your project. We
          look forward to hearing from you and hope that we can work together to
          achieve your goals.
        </p>

        <Section />
      </Container>
    </main>
  );
}

export default ApiPage;
