// app/navbar.tsx
"use client";

import Link from "next/link";
import Container from "../components/container";

function Navbar() {
  return (
    <header className="h-20 flex justify-center sticky top-0 z-10 bg-white/30 backdrop-blur-sm">
      <Container className="p-4 flex justify-between items-center  rounded-b-3xl h-full ">
        <Link href="/" className="font-semibold text-3xl">
          isave
        </Link>

        <nav>
          <ul className="flex gap-2 items-center">
            <li className="p-2 rounded-full">
              <Link
                href="/how-to-get-url"
                className="hover:border-black border-b-2 border-transparent"
              >
                How to get url?
              </Link>
            </li>

            <li className="p-2 rounded-full">
              <a
                target="_blank"
                rel="noreferrer"
                href="https://github.com/devyuji/isave"
                className="flex gap-1 items-center hover:border-black border-b-2 border-transparent"
              >
                Github
                <span>
                  <svg
                    viewBox="0 0 24 24"
                    width="20"
                    height="20"
                    stroke="currentColor"
                    strokeWidth="2"
                    fill="none"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <line x1="7" y1="17" x2="17" y2="7"></line>
                    <polyline points="7 7 17 7 17 17"></polyline>
                  </svg>
                </span>
              </a>
            </li>
          </ul>
        </nav>
      </Container>
    </header>
  );
}

export default Navbar;

// src/components/navbar.svelte
<script lang="ts">
  import { slide } from "svelte/transition";
  export const links = [
    {
      label: "downloader",
      url: "/",
    },
    {
      label: "preview",
      url: "/preview",
    },
    {
      label: "github",
      url: "https://github.com/devyuji/isave",
    },
  ];

  export const sticky = true;

  let menu = false;
</script>

<header class="container">
  <div>
    <h1>isave</h1>
  </div>

  <div class="menu">
    <button type="button" on:click={() => (menu = !menu)}>
      <svg
        viewBox="0 0 24 24"
        width="24"
        height="24"
        stroke="currentColor"
        stroke-width="2"
        fill="none"
        stroke-linecap="round"
        stroke-linejoin="round"
        class="css-i6dzq1"
        ><line x1="3" y1="12" x2="21" y2="12" /><line
          x1="3"
          y1="6"
          x2="21"
          y2="6"
        /><line x1="3" y1="18" x2="21" y2="18" /></svg
      >
    </button>
  </div>

  <nav class="desktop">
    <ul class="nav-list">
      {#each links as link}
        <li>
          <a href={link.url}>{link.label}</a>
        </li>
      {/each}
    </ul>
  </nav>

  {#if menu}
    <nav class="mobile" transition:slide>
      <ul class="nav-list">
        {#each links as link}
          <li>
            <a href={link.url} on:click={() => (menu = false)}>{link.label}</a>
          </li>
        {/each}
      </ul>

      <button
        type="button"
        aria-label="close menu"
        on:click={() => (menu = false)}
      >
        <svg
          viewBox="0 0 24 24"
          width="24"
          height="24"
          stroke="currentColor"
          stroke-width="2"
          fill="none"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="css-i6dzq1"
          ><line x1="18" y1="6" x2="6" y2="18" /><line
            x1="6"
            y1="6"
            x2="18"
            y2="18"
          /></svg
        >
      </button>
    </nav>
  {/if}
</header>

<style>
  .container {
    height: 5rem;

    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 2rem;

    position: relative;
  }

  .container h1 {
    font-weight: var(--ft-semi-bold);
  }

  .nav-list {
    display: flex;
    gap: 1rem;
    list-style: none;

    font-weight: var(--ft-medium);
    font-size: 1.2rem;
  }

  .menu {
    display: none;
  }

  .menu button {
    border: none;
    background-color: transparent;
  }

  .mobile {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: white;
    z-index: 100;

    display: none;
  }

  .mobile button {
    position: absolute;
    top: 2rem;
    right: 2rem;

    border: none;
    background-color: transparent;
  }

  @media (max-width: 500px) {
    .desktop {
      display: none;
    }

    .mobile,
    .menu {
      display: block;
    }

    .nav-list {
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: 100%;

      text-transform: capitalize;
      font-size: 2rem;
    }
  }
</style>
